/**
 * 오늘의 부적 · fortune-data.js
 * 기획서 v3.0 + 운세_키워드요소.txt 기반 마스터 데이터
 *
 * [필드]
 *  id       파일명·코드용 고유 식별자 (전 카테고리에서 중복 없음)
 *  name     사용자에게 보이는 이름
 *  meaning  도감·상세 설명용 한 줄 의미
 *  tags     의미 태그 (가중치 산출·검색·필터용)
 *  subject  (그림 소재만) AI 프롬프트의 SUBJECT 슬롯에 넣을 영문 소재명
 *  weights  운세별 등장 가중치 1~5 (태그 매핑으로 자동 산출 후 일부 수동 보정)
 *  images   스타일별 이미지 경로(WebP). 파일이 아직 없으면 앱에서 다른 스타일 → 텍스트 배지 순으로 폴백
 *  hex      (컬러만) 대표 색상 코드 / value (숫자·시간만) 원래 값
 *
 * [변경 사항]
 *  - pegasus: 이름은 Y2K 스티커 문구에 맞춰 "날개 달린 유니콘" 유지 (id는 파일명 호환 위해 pegasus 유지)
 *  - 행운의 숫자: 1~99 코드 생성 대신 큐레이션된 20개 목록 사용
 *  - 컬러·단어·숫자·시간에 id / meaning / tags / weights / images 추가
 *  - 시간 value는 24시간제("14:14"), name은 표시용("오후 02:14")
 *  - clover_item ↔ four_leaf_clover 동시 출현 금지 (EXCLUSIONS)
 */

const FORTUNE_TYPES = [
  { id: "job",    name: "취업운",     tone: ["기회", "집중", "준비", "성취"] },
  { id: "love",   name: "연애운",     tone: ["호감", "표현", "대화", "우연"] },
  { id: "money",  name: "금전운",     tone: ["가치", "균형", "계획", "관리"] },
  { id: "people", name: "인간관계운", tone: ["공감", "배려", "신뢰", "연결"] },
  { id: "study",  name: "학업운",     tone: ["집중", "몰입", "질문", "완성"] },
  { id: "daily",  name: "종합운",     tone: ["행운", "발견", "여유", "변화"] },
];

const STICKER_STYLES = [
  { id: "y2k",    name: "Y2K Lucky Pop" },
  { id: "retro",  name: "Retro Ephemera" },
  { id: "doodle", name: "Lucky Doodle" },
];

// 카드에 뽑히는 순서 = 이 배열 순서
const CATEGORIES = [
  { id: "number", name: "행운의 숫자", folder: "numbers" },
  { id: "color",  name: "행운의 컬러", folder: "colors" },
  { id: "word",   name: "행운의 단어", folder: "words" },
  { id: "item",   name: "행운의 아이템", folder: "items" },
  { id: "animal", name: "행운의 동물", folder: "animals" },
  { id: "place",  name: "행운의 장소", folder: "places" },
  { id: "time",   name: "행운의 시간", folder: "times" },
  { id: "symbol", name: "행운의 심볼", folder: "symbols" },
];

// 한 장의 부적에 함께 나오면 안 되는 조합 (앞이 먼저 뽑히면 뒤는 재추첨)
const EXCLUSIONS = [
  ["clover_item", "four_leaf_clover"],
];

const FORTUNE_DATA = {
  number: [
    {"id": "num_001", "name": "1", "value": 1, "meaning": "무엇이든 처음 시작하기 좋은 숫자", "tags": ["새출발", "용기"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_001-y2k.webp", "retro": "assets/stickers/numbers/num_001-retro.webp", "doodle": "assets/stickers/numbers/num_001-doodle.webp"}},
    {"id": "num_003", "name": "3", "value": 3, "meaning": "균형과 조화를 부르는 숫자", "tags": ["조화", "연결"], "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_003-y2k.webp", "retro": "assets/stickers/numbers/num_003-retro.webp", "doodle": "assets/stickers/numbers/num_003-doodle.webp"}},
    {"id": "num_005", "name": "5", "value": 5, "meaning": "변화와 활력을 부르는 숫자", "tags": ["변화", "즐거움"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/numbers/num_005-y2k.webp", "retro": "assets/stickers/numbers/num_005-retro.webp", "doodle": "assets/stickers/numbers/num_005-doodle.webp"}},
    {"id": "num_007", "name": "7", "value": 7, "meaning": "대표적인 행운의 숫자", "tags": ["행운", "기적"], "weights": {"job": 1, "love": 3, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/numbers/num_007-y2k.webp", "retro": "assets/stickers/numbers/num_007-retro.webp", "doodle": "assets/stickers/numbers/num_007-doodle.webp"}},
    {"id": "num_008", "name": "8", "value": 8, "meaning": "재물과 번영을 부르는 숫자", "tags": ["재물", "풍요"], "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_008-y2k.webp", "retro": "assets/stickers/numbers/num_008-retro.webp", "doodle": "assets/stickers/numbers/num_008-doodle.webp"}},
    {"id": "num_009", "name": "9", "value": 9, "meaning": "하나의 흐름을 완성하는 숫자", "tags": ["완성", "성취"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_009-y2k.webp", "retro": "assets/stickers/numbers/num_009-retro.webp", "doodle": "assets/stickers/numbers/num_009-doodle.webp"}},
    {"id": "num_010", "name": "10", "value": 10, "meaning": "만점의 기운을 담은 숫자", "tags": ["합격", "완성"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_010-y2k.webp", "retro": "assets/stickers/numbers/num_010-retro.webp", "doodle": "assets/stickers/numbers/num_010-doodle.webp"}},
    {"id": "num_011", "name": "11", "value": 11, "meaning": "나란히 선 두 개의 1, 좋은 인연의 숫자", "tags": ["인연", "단짝"], "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_011-y2k.webp", "retro": "assets/stickers/numbers/num_011-retro.webp", "doodle": "assets/stickers/numbers/num_011-doodle.webp"}},
    {"id": "num_014", "name": "14", "value": 14, "meaning": "사랑을 전하기 좋은 숫자", "tags": ["사랑", "고백"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_014-y2k.webp", "retro": "assets/stickers/numbers/num_014-retro.webp", "doodle": "assets/stickers/numbers/num_014-doodle.webp"}},
    {"id": "num_018", "name": "18", "value": 18, "meaning": "힘차게 치고 나가는 숫자", "tags": ["돌파", "도전"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_018-y2k.webp", "retro": "assets/stickers/numbers/num_018-retro.webp", "doodle": "assets/stickers/numbers/num_018-doodle.webp"}},
    {"id": "num_021", "name": "21", "value": 21, "meaning": "성장과 성숙을 부르는 숫자", "tags": ["도약", "성취"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_021-y2k.webp", "retro": "assets/stickers/numbers/num_021-retro.webp", "doodle": "assets/stickers/numbers/num_021-doodle.webp"}},
    {"id": "num_024", "name": "24", "value": 24, "meaning": "하루를 꽉 채우는 숫자", "tags": ["꾸준함", "성실"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_024-y2k.webp", "retro": "assets/stickers/numbers/num_024-retro.webp", "doodle": "assets/stickers/numbers/num_024-doodle.webp"}},
    {"id": "num_027", "name": "27", "value": 27, "meaning": "직관이 깨어나는 숫자", "tags": ["직관", "영감"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_027-y2k.webp", "retro": "assets/stickers/numbers/num_027-retro.webp", "doodle": "assets/stickers/numbers/num_027-doodle.webp"}},
    {"id": "num_033", "name": "33", "value": 33, "meaning": "다정한 소통을 부르는 숫자", "tags": ["대화", "공감"], "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_033-y2k.webp", "retro": "assets/stickers/numbers/num_033-retro.webp", "doodle": "assets/stickers/numbers/num_033-doodle.webp"}},
    {"id": "num_042", "name": "42", "value": 42, "meaning": "질문의 답을 찾게 해주는 숫자", "tags": ["지혜", "발견"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_042-y2k.webp", "retro": "assets/stickers/numbers/num_042-retro.webp", "doodle": "assets/stickers/numbers/num_042-doodle.webp"}},
    {"id": "num_055", "name": "55", "value": 55, "meaning": "변화가 겹겹이 찾아오는 숫자", "tags": ["변화", "기회"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/numbers/num_055-y2k.webp", "retro": "assets/stickers/numbers/num_055-retro.webp", "doodle": "assets/stickers/numbers/num_055-doodle.webp"}},
    {"id": "num_077", "name": "77", "value": 77, "meaning": "행운이 두 배로 겹치는 숫자", "tags": ["대행운", "축복"], "weights": {"job": 1, "love": 3, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/numbers/num_077-y2k.webp", "retro": "assets/stickers/numbers/num_077-retro.webp", "doodle": "assets/stickers/numbers/num_077-doodle.webp"}},
    {"id": "num_088", "name": "88", "value": 88, "meaning": "재물운이 두 배로 겹치는 숫자", "tags": ["재물", "대박"], "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_088-y2k.webp", "retro": "assets/stickers/numbers/num_088-retro.webp", "doodle": "assets/stickers/numbers/num_088-doodle.webp"}},
    {"id": "num_099", "name": "99", "value": 99, "meaning": "끝까지 해내는 숫자", "tags": ["목표", "성취"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_099-y2k.webp", "retro": "assets/stickers/numbers/num_099-retro.webp", "doodle": "assets/stickers/numbers/num_099-doodle.webp"}},
    {"id": "num_100", "name": "100", "value": 100, "meaning": "완벽한 만점의 숫자", "tags": ["합격", "완성"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/numbers/num_100-y2k.webp", "retro": "assets/stickers/numbers/num_100-retro.webp", "doodle": "assets/stickers/numbers/num_100-doodle.webp"}},
  ],
  color: [
    {"id": "cherry_pink", "name": "체리 핫핑크", "hex": "#FF2E7E", "meaning": "자신감 넘치는 Y2K 팝 에너지", "tags": ["자신감", "매력", "설렘"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/cherry_pink-y2k.webp", "retro": "assets/stickers/colors/cherry_pink-retro.webp", "doodle": "assets/stickers/colors/cherry_pink-doodle.webp"}},
    {"id": "butter_yellow", "name": "버터 옐로우", "hex": "#FFE156", "meaning": "긴장을 사르르 녹이는 온기", "tags": ["위로", "편안함", "긍정"], "weights": {"job": 1, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/butter_yellow-y2k.webp", "retro": "assets/stickers/colors/butter_yellow-retro.webp", "doodle": "assets/stickers/colors/butter_yellow-doodle.webp"}},
    {"id": "sky_cyan", "name": "스카이 시안", "hex": "#00D2FF", "meaning": "하늘처럼 시야가 트이는 청량감", "tags": ["전망", "자유", "집중"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/colors/sky_cyan-y2k.webp", "retro": "assets/stickers/colors/sky_cyan-retro.webp", "doodle": "assets/stickers/colors/sky_cyan-doodle.webp"}},
    {"id": "apple_mint", "name": "애플 민트", "hex": "#42E2B8", "meaning": "지친 심신을 리프레시하는 활력", "tags": ["충전", "힐링", "새출발"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/apple_mint-y2k.webp", "retro": "assets/stickers/colors/apple_mint-retro.webp", "doodle": "assets/stickers/colors/apple_mint-doodle.webp"}},
    {"id": "dream_lavender", "name": "드림 라벤더", "hex": "#B19FFB", "meaning": "복잡한 생각을 가라앉히는 감수성", "tags": ["평온", "직관", "영감"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 4}, "images": {"y2k": "assets/stickers/colors/dream_lavender-y2k.webp", "retro": "assets/stickers/colors/dream_lavender-retro.webp", "doodle": "assets/stickers/colors/dream_lavender-doodle.webp"}},
    {"id": "champagne_gold", "name": "샴페인 골드", "hex": "#F6B343", "meaning": "재물과 이득을 끌어당기는 황금빛", "tags": ["재물", "풍요", "황금"], "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/champagne_gold-y2k.webp", "retro": "assets/stickers/colors/champagne_gold-retro.webp", "doodle": "assets/stickers/colors/champagne_gold-doodle.webp"}},
    {"id": "forest_emerald", "name": "포레스트 에메랄드", "hex": "#10B981", "meaning": "깊은 숲처럼 흔들리지 않는 뚝심", "tags": ["꾸준함", "성실", "믿음"], "weights": {"job": 5, "love": 1, "money": 1, "people": 3, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/colors/forest_emerald-y2k.webp", "retro": "assets/stickers/colors/forest_emerald-retro.webp", "doodle": "assets/stickers/colors/forest_emerald-doodle.webp"}},
    {"id": "peach_coral", "name": "피치 코랄", "hex": "#FF7B72", "meaning": "첫인상부터 호감을 부르는 달콤함", "tags": ["호감", "매력", "대화"], "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/peach_coral-y2k.webp", "retro": "assets/stickers/colors/peach_coral-retro.webp", "doodle": "assets/stickers/colors/peach_coral-doodle.webp"}},
    {"id": "deep_navy", "name": "딥 네이비", "hex": "#1E293B", "meaning": "냉철한 판단력과 실수 없는 집중력", "tags": ["집중", "결단", "몰입"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/colors/deep_navy-y2k.webp", "retro": "assets/stickers/colors/deep_navy-retro.webp", "doodle": "assets/stickers/colors/deep_navy-doodle.webp"}},
    {"id": "milk_cream", "name": "밀크 크림", "hex": "#FFF8E7", "meaning": "순수하고 편안한 여백과 조화", "tags": ["조화", "편안함", "순수"], "weights": {"job": 1, "love": 3, "money": 1, "people": 3, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/colors/milk_cream-y2k.webp", "retro": "assets/stickers/colors/milk_cream-retro.webp", "doodle": "assets/stickers/colors/milk_cream-doodle.webp"}},
    {"id": "tangerine", "name": "탠저린 오렌지", "hex": "#FF8811", "meaning": "통통 튀는 기분 좋은 비타민 에너지", "tags": ["즐거움", "긍정", "추진"], "weights": {"job": 3, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/tangerine-y2k.webp", "retro": "assets/stickers/colors/tangerine-retro.webp", "doodle": "assets/stickers/colors/tangerine-doodle.webp"}},
    {"id": "ruby_red", "name": "루비 레드", "hex": "#E63946", "meaning": "거침없이 전진하는 뜨거운 열정", "tags": ["열정", "도전", "파워"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/ruby_red-y2k.webp", "retro": "assets/stickers/colors/ruby_red-retro.webp", "doodle": "assets/stickers/colors/ruby_red-doodle.webp"}},
    {"id": "baby_pink", "name": "베이비 핑크", "hex": "#FFCCD5", "meaning": "사랑스럽고 포근한 애정운", "tags": ["사랑", "애정", "다정"], "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/baby_pink-y2k.webp", "retro": "assets/stickers/colors/baby_pink-retro.webp", "doodle": "assets/stickers/colors/baby_pink-doodle.webp"}},
    {"id": "pistachio", "name": "피스타치오 그린", "hex": "#99D98C", "meaning": "과하지 않고 안도감을 주는 그린", "tags": ["무탈", "균형", "여유"], "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/pistachio-y2k.webp", "retro": "assets/stickers/colors/pistachio-retro.webp", "doodle": "assets/stickers/colors/pistachio-doodle.webp"}},
    {"id": "royal_purple", "name": "로열 퍼플", "hex": "#7209B7", "meaning": "남다른 기품과 고귀한 아우라", "tags": ["매력", "가치", "자신감"], "weights": {"job": 1, "love": 5, "money": 3, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/royal_purple-y2k.webp", "retro": "assets/stickers/colors/royal_purple-retro.webp", "doodle": "assets/stickers/colors/royal_purple-doodle.webp"}},
    {"id": "soft_charcoal", "name": "소프트 차콜", "hex": "#4A4E69", "meaning": "들뜬 마음을 차분히 정돈하는 침착함", "tags": ["집중", "평온", "관리"], "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/colors/soft_charcoal-y2k.webp", "retro": "assets/stickers/colors/soft_charcoal-retro.webp", "doodle": "assets/stickers/colors/soft_charcoal-doodle.webp"}},
    {"id": "vintage_rose", "name": "빈티지 로즈", "hex": "#C97A7E", "meaning": "그윽하고 질리지 않는 우아함", "tags": ["낭만", "인연", "향기"], "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/colors/vintage_rose-y2k.webp", "retro": "assets/stickers/colors/vintage_rose-retro.webp", "doodle": "assets/stickers/colors/vintage_rose-doodle.webp"}},
    {"id": "ocean_blue", "name": "오션 블루", "hex": "#0077B6", "meaning": "바다처럼 너그럽게 품는 지혜", "tags": ["지혜", "너그러움", "공감"], "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/colors/ocean_blue-y2k.webp", "retro": "assets/stickers/colors/ocean_blue-retro.webp", "doodle": "assets/stickers/colors/ocean_blue-doodle.webp"}},
    {"id": "sunshine_yellow", "name": "선샤인 옐로우", "hex": "#FFD166", "meaning": "구름을 뚫고 나오는 따스한 햇살", "tags": ["희망", "광명", "행복"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/sunshine_yellow-y2k.webp", "retro": "assets/stickers/colors/sunshine_yellow-retro.webp", "doodle": "assets/stickers/colors/sunshine_yellow-doodle.webp"}},
    {"id": "popping_lime", "name": "팝핑 라임", "hex": "#A7C957", "meaning": "묵은 정체를 날려버리는 사이다 청량감", "tags": ["돌파", "해방감", "변화"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/colors/popping_lime-y2k.webp", "retro": "assets/stickers/colors/popping_lime-retro.webp", "doodle": "assets/stickers/colors/popping_lime-doodle.webp"}},
  ],
  word: [
    {"id": "courage", "name": "용기", "meaning": "망설이던 한 걸음을 내딛게 하는 힘", "tags": ["용기", "도전"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/courage-y2k.webp", "retro": "assets/stickers/words/courage-retro.webp", "doodle": "assets/stickers/words/courage-doodle.webp"}},
    {"id": "timing", "name": "타이밍", "meaning": "딱 맞는 순간이 나를 향해 오고 있어요", "tags": ["타이밍", "기회"], "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/timing-y2k.webp", "retro": "assets/stickers/words/timing-retro.webp", "doodle": "assets/stickers/words/timing-doodle.webp"}},
    {"id": "flutter", "name": "설렘", "meaning": "작은 두근거림이 새로운 일을 불러와요", "tags": ["설렘", "우연"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/flutter-y2k.webp", "retro": "assets/stickers/words/flutter-retro.webp", "doodle": "assets/stickers/words/flutter-doodle.webp"}},
    {"id": "jackpot", "name": "대박", "meaning": "생각보다 큰 행운이 굴러 들어와요", "tags": ["대박", "재물"], "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/jackpot-y2k.webp", "retro": "assets/stickers/words/jackpot-retro.webp", "doodle": "assets/stickers/words/jackpot-doodle.webp"}},
    {"id": "immersion", "name": "몰입", "meaning": "한 가지에 푹 빠질수록 결과가 빛나요", "tags": ["몰입", "집중"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/words/immersion-y2k.webp", "retro": "assets/stickers/words/immersion-retro.webp", "doodle": "assets/stickers/words/immersion-doodle.webp"}},
    {"id": "calm", "name": "평온", "meaning": "흔들리지 않는 마음이 나를 지켜줘요", "tags": ["평온", "무탈"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/calm-y2k.webp", "retro": "assets/stickers/words/calm-retro.webp", "doodle": "assets/stickers/words/calm-doodle.webp"}},
    {"id": "connection", "name": "연결", "meaning": "좋은 사람과 기회가 이어지는 날", "tags": ["연결", "인연"], "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/connection-y2k.webp", "retro": "assets/stickers/words/connection-retro.webp", "doodle": "assets/stickers/words/connection-doodle.webp"}},
    {"id": "shine", "name": "빛남", "meaning": "가만히 있어도 존재감이 드러나요", "tags": ["매력", "자신감"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/shine-y2k.webp", "retro": "assets/stickers/words/shine-retro.webp", "doodle": "assets/stickers/words/shine-doodle.webp"}},
    {"id": "breakthrough", "name": "돌파", "meaning": "막혀 있던 일이 시원하게 뚫려요", "tags": ["돌파", "해결"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/breakthrough-y2k.webp", "retro": "assets/stickers/words/breakthrough-retro.webp", "doodle": "assets/stickers/words/breakthrough-doodle.webp"}},
    {"id": "gift", "name": "선물", "meaning": "뜻밖의 기쁜 선물이 찾아와요", "tags": ["선물", "우연"], "weights": {"job": 1, "love": 5, "money": 3, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/gift-y2k.webp", "retro": "assets/stickers/words/gift-retro.webp", "doodle": "assets/stickers/words/gift-doodle.webp"}},
    {"id": "leap", "name": "도약", "meaning": "한 단계 높이 뛰어오를 준비 완료", "tags": ["도약", "성취"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/leap-y2k.webp", "retro": "assets/stickers/words/leap-retro.webp", "doodle": "assets/stickers/words/leap-doodle.webp"}},
    {"id": "conviction", "name": "확신", "meaning": "내 선택을 믿어도 좋은 날", "tags": ["확신", "결단"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/conviction-y2k.webp", "retro": "assets/stickers/words/conviction-retro.webp", "doodle": "assets/stickers/words/conviction-doodle.webp"}},
    {"id": "ease", "name": "여유", "meaning": "서두르지 않아도 다 잘 풀려요", "tags": ["여유", "휴식"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/ease-y2k.webp", "retro": "assets/stickers/words/ease-retro.webp", "doodle": "assets/stickers/words/ease-doodle.webp"}},
    {"id": "intuition", "name": "직관", "meaning": "첫 느낌이 정답에 가까워요", "tags": ["직관", "통찰"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/words/intuition-y2k.webp", "retro": "assets/stickers/words/intuition-retro.webp", "doodle": "assets/stickers/words/intuition-doodle.webp"}},
    {"id": "harmony", "name": "조화", "meaning": "주변과 자연스럽게 어우러져요", "tags": ["조화", "원만"], "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/harmony-y2k.webp", "retro": "assets/stickers/words/harmony-retro.webp", "doodle": "assets/stickers/words/harmony-doodle.webp"}},
    {"id": "completion", "name": "완성", "meaning": "미뤄둔 일을 마무리하기 좋은 날", "tags": ["완성", "성취"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/words/completion-y2k.webp", "retro": "assets/stickers/words/completion-retro.webp", "doodle": "assets/stickers/words/completion-doodle.webp"}},
    {"id": "fruition", "name": "결실", "meaning": "쌓아온 노력이 열매를 맺어요", "tags": ["결실", "재물"], "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/fruition-y2k.webp", "retro": "assets/stickers/words/fruition-retro.webp", "doodle": "assets/stickers/words/fruition-doodle.webp"}},
    {"id": "kindness", "name": "다정", "meaning": "다정한 한마디가 큰 힘이 돼요", "tags": ["다정", "배려"], "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/kindness-y2k.webp", "retro": "assets/stickers/words/kindness-retro.webp", "doodle": "assets/stickers/words/kindness-doodle.webp"}},
    {"id": "vitality", "name": "활력", "meaning": "몸과 마음에 에너지가 차올라요", "tags": ["충전", "열정"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/words/vitality-y2k.webp", "retro": "assets/stickers/words/vitality-retro.webp", "doodle": "assets/stickers/words/vitality-doodle.webp"}},
    {"id": "healing", "name": "힐링", "meaning": "지친 마음이 사르르 풀려요", "tags": ["힐링", "위로"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/healing-y2k.webp", "retro": "assets/stickers/words/healing-retro.webp", "doodle": "assets/stickers/words/healing-doodle.webp"}},
    {"id": "friendship", "name": "우정", "meaning": "곁에 있는 친구가 행운을 가져와요", "tags": ["우정", "단짝"], "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/friendship-y2k.webp", "retro": "assets/stickers/words/friendship-retro.webp", "doodle": "assets/stickers/words/friendship-doodle.webp"}},
    {"id": "love", "name": "사랑", "meaning": "사랑을 주고받기 좋은 날", "tags": ["사랑", "애정"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/love-y2k.webp", "retro": "assets/stickers/words/love-retro.webp", "doodle": "assets/stickers/words/love-doodle.webp"}},
    {"id": "blessing", "name": "축복", "meaning": "작은 일에도 축복이 깃들어요", "tags": ["축복", "행복"], "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/blessing-y2k.webp", "retro": "assets/stickers/words/blessing-retro.webp", "doodle": "assets/stickers/words/blessing-doodle.webp"}},
    {"id": "miracle", "name": "기적", "meaning": "믿기 어려운 좋은 일이 일어나요", "tags": ["기적", "대행운"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/miracle-y2k.webp", "retro": "assets/stickers/words/miracle-retro.webp", "doodle": "assets/stickers/words/miracle-doodle.webp"}},
    {"id": "inspiration", "name": "영감", "meaning": "번뜩이는 아이디어가 떠올라요", "tags": ["영감", "발견"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/words/inspiration-y2k.webp", "retro": "assets/stickers/words/inspiration-retro.webp", "doodle": "assets/stickers/words/inspiration-doodle.webp"}},
    {"id": "happiness", "name": "행복", "meaning": "평범한 순간이 행복으로 채워져요", "tags": ["행복", "긍정"], "weights": {"job": 1, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/happiness-y2k.webp", "retro": "assets/stickers/words/happiness-retro.webp", "doodle": "assets/stickers/words/happiness-doodle.webp"}},
    {"id": "safe_day", "name": "무탈", "meaning": "큰 걱정 없이 무사히 흘러가는 하루", "tags": ["무탈", "안전"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/safe_day-y2k.webp", "retro": "assets/stickers/words/safe_day-retro.webp", "doodle": "assets/stickers/words/safe_day-doodle.webp"}},
    {"id": "soar", "name": "비상", "meaning": "더 높은 곳으로 날아오를 시간", "tags": ["비상", "포부"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/words/soar-y2k.webp", "retro": "assets/stickers/words/soar-retro.webp", "doodle": "assets/stickers/words/soar-doodle.webp"}},
    {"id": "sparkle", "name": "반짝임", "meaning": "작은 반짝임들이 모여 큰 빛이 돼요", "tags": ["빛", "매력"], "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/words/sparkle-y2k.webp", "retro": "assets/stickers/words/sparkle-retro.webp", "doodle": "assets/stickers/words/sparkle-doodle.webp"}},
    {"id": "release", "name": "해방", "meaning": "묵은 걱정을 훌훌 털어내요", "tags": ["해방감", "자유"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/words/release-y2k.webp", "retro": "assets/stickers/words/release-retro.webp", "doodle": "assets/stickers/words/release-doodle.webp"}},
  ],
  item: [
    {"id": "key", "name": "황금 열쇠", "meaning": "닫혀 있던 기회의 문을 활짝 여는 만능 키", "tags": ["해결", "열쇠", "합격"], "subject": "golden key", "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/items/key-y2k.webp", "retro": "assets/stickers/items/key-retro.webp", "doodle": "assets/stickers/items/key-doodle.webp"}},
    {"id": "clover_item", "name": "네잎클로버 책갈피", "meaning": "찰나의 행운을 책 속에 단단히 붙잡아둠", "tags": ["행운", "지혜", "간직"], "subject": "four-leaf clover bookmark", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/items/clover_item-y2k.webp", "retro": "assets/stickers/items/clover_item-retro.webp", "doodle": "assets/stickers/items/clover_item-doodle.webp"}},
    {"id": "vintage_camera", "name": "빈티지 디카", "meaning": "오늘 가장 예쁜 순간만을 기억해줄 레트로 카메라", "tags": ["추억", "기록", "설렘"], "subject": "Y2K compact digital camera", "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/items/vintage_camera-y2k.webp", "retro": "assets/stickers/items/vintage_camera-retro.webp", "doodle": "assets/stickers/items/vintage_camera-doodle.webp"}},
    {"id": "cassette", "name": "믹스테이프 카세트", "meaning": "나만의 기분 좋은 템포와 리듬을 지켜주는 음악 테이프", "tags": ["감성", "음악", "힐링"], "subject": "mixtape cassette tape", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/items/cassette-y2k.webp", "retro": "assets/stickers/items/cassette-retro.webp", "doodle": "assets/stickers/items/cassette-doodle.webp"}},
    {"id": "coffee_mug", "name": "따뜻한 머그컵", "meaning": "김이 모락모락 피어오르는 달콤한 온기", "tags": ["여유", "충전", "위로"], "subject": "steaming coffee mug", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/items/coffee_mug-y2k.webp", "retro": "assets/stickers/items/coffee_mug-retro.webp", "doodle": "assets/stickers/items/coffee_mug-doodle.webp"}},
    {"id": "sparkle_ring", "name": "약속의 반지", "meaning": "변치 않는 믿음과 서로를 향한 단단한 서약", "tags": ["약속", "신뢰", "인연"], "subject": "sparkling promise ring", "weights": {"job": 1, "love": 5, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/sparkle_ring-y2k.webp", "retro": "assets/stickers/items/sparkle_ring-retro.webp", "doodle": "assets/stickers/items/sparkle_ring-doodle.webp"}},
    {"id": "magic_wand", "name": "마법 요술봉", "meaning": "소원을 톡 이루어주는 별/하트 마법봉", "tags": ["소원", "기적", "마법"], "subject": "star magic wand", "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/items/magic_wand-y2k.webp", "retro": "assets/stickers/items/magic_wand-retro.webp", "doodle": "assets/stickers/items/magic_wand-doodle.webp"}},
    {"id": "lucky_coin", "name": "행운의 금화", "meaning": "지갑 속에 재물의 기운을 채워주는 반짝이는 황금 동전", "tags": ["재물", "금전", "풍요"], "subject": "shiny gold lucky coin", "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/lucky_coin-y2k.webp", "retro": "assets/stickers/items/lucky_coin-retro.webp", "doodle": "assets/stickers/items/lucky_coin-doodle.webp"}},
    {"id": "pink_diary", "name": "핑크 다이어리", "meaning": "적는 대로 현실이 되는 나만의 버킷리스트 다이어리", "tags": ["기록", "계획", "실현"], "subject": "pink diary with lock", "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/items/pink_diary-y2k.webp", "retro": "assets/stickers/items/pink_diary-retro.webp", "doodle": "assets/stickers/items/pink_diary-doodle.webp"}},
    {"id": "retro_headphone", "name": "레트로 헤드폰", "meaning": "세상의 소음을 차단하고 오롯이 나에게 집중", "tags": ["몰입", "음악", "휴식"], "subject": "retro headphones", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 4}, "images": {"y2k": "assets/stickers/items/retro_headphone-y2k.webp", "retro": "assets/stickers/items/retro_headphone-retro.webp", "doodle": "assets/stickers/items/retro_headphone-doodle.webp"}},
    {"id": "silk_ribbon", "name": "행운의 분홍 리본", "meaning": "소중한 인연의 끈을 단단하고 예쁘게 묶어줌", "tags": ["인연", "매듭", "선물"], "subject": "pink silk ribbon bow", "weights": {"job": 1, "love": 5, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/silk_ribbon-y2k.webp", "retro": "assets/stickers/items/silk_ribbon-retro.webp", "doodle": "assets/stickers/items/silk_ribbon-doodle.webp"}},
    {"id": "perfume", "name": "매혹의 향수병", "meaning": "은은한 아우라를 뿜어내는 빈티지 크리스탈 향수병", "tags": ["매력", "향기", "호감"], "subject": "vintage crystal perfume bottle", "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/perfume-y2k.webp", "retro": "assets/stickers/items/perfume-retro.webp", "doodle": "assets/stickers/items/perfume-doodle.webp"}},
    {"id": "classic_glasses", "name": "스마트 안경", "meaning": "본질을 꿰뚫어 보는 지적인 통찰력", "tags": ["통찰", "지혜", "집중"], "subject": "round eyeglasses", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/items/classic_glasses-y2k.webp", "retro": "assets/stickers/items/classic_glasses-retro.webp", "doodle": "assets/stickers/items/classic_glasses-doodle.webp"}},
    {"id": "love_letter", "name": "봉인된 편지", "meaning": "붉은 실링왁스가 찍힌 기쁜 소식의 편지", "tags": ["소식", "합격통지", "고백"], "subject": "envelope with red wax seal", "weights": {"job": 5, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/love_letter-y2k.webp", "retro": "assets/stickers/items/love_letter-retro.webp", "doodle": "assets/stickers/items/love_letter-doodle.webp"}},
    {"id": "hand_mirror", "name": "요술 손거울", "meaning": "가장 빛나는 얼굴을 비춰주는 엔틱 손거울", "tags": ["미모", "자존감", "자신감"], "subject": "antique hand mirror", "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/hand_mirror-y2k.webp", "retro": "assets/stickers/items/hand_mirror-retro.webp", "doodle": "assets/stickers/items/hand_mirror-doodle.webp"}},
    {"id": "aroma_candle", "name": "아로마 캔들", "meaning": "은은한 불빛과 향기로 마음을 보듬는 향초", "tags": ["안식", "위로", "빛"], "subject": "aroma candle in a jar", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/items/aroma_candle-y2k.webp", "retro": "assets/stickers/items/aroma_candle-retro.webp", "doodle": "assets/stickers/items/aroma_candle-doodle.webp"}},
    {"id": "crystal_ball", "name": "크리스탈 구슬", "meaning": "미래를 맑게 비춰주는 영롱한 유리 구슬", "tags": ["미래", "예지", "신비"], "subject": "crystal ball on a stand", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/items/crystal_ball-y2k.webp", "retro": "assets/stickers/items/crystal_ball-retro.webp", "doodle": "assets/stickers/items/crystal_ball-doodle.webp"}},
    {"id": "hourglass", "name": "미니 모래시계", "meaning": "가장 좋은 타이밍을 알려주는 반짝이는 모래시계", "tags": ["시간", "효율", "타이밍"], "subject": "sparkly mini hourglass", "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/items/hourglass-y2k.webp", "retro": "assets/stickers/items/hourglass-retro.webp", "doodle": "assets/stickers/items/hourglass-doodle.webp"}},
    {"id": "skateboard", "name": "Y2K 스케이트보드", "meaning": "장애물을 시원하게 뛰어넘는 그래피티 보드", "tags": ["스피드", "돌파", "도전"], "subject": "graffiti skateboard", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/items/skateboard-y2k.webp", "retro": "assets/stickers/items/skateboard-retro.webp", "doodle": "assets/stickers/items/skateboard-doodle.webp"}},
    {"id": "lollipop", "name": "무지개 롤리팝", "meaning": "한 입에 기분이 좋아지는 알록달록 달콤함", "tags": ["달콤함", "동심", "미소"], "subject": "rainbow swirl lollipop", "weights": {"job": 1, "love": 3, "money": 1, "people": 3, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/items/lollipop-y2k.webp", "retro": "assets/stickers/items/lollipop-retro.webp", "doodle": "assets/stickers/items/lollipop-doodle.webp"}},
  ],
  animal: [
    {"id": "fox", "name": "지혜로운 붉은여우", "meaning": "빠른 눈치와 유연한 재치로 상황을 넘김", "tags": ["재치", "임기응변", "매력"], "subject": "small clever red fox", "weights": {"job": 3, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/fox-y2k.webp", "retro": "assets/stickers/animals/fox-retro.webp", "doodle": "assets/stickers/animals/fox-doodle.webp"}},
    {"id": "bunny", "name": "깡총 행운 토끼", "meaning": "두려움 없이 껑충 뛰어올라 높은 곳으로 도약", "tags": ["도약", "귀여움", "스피드"], "subject": "hopping lucky bunny", "weights": {"job": 5, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/bunny-y2k.webp", "retro": "assets/stickers/animals/bunny-retro.webp", "doodle": "assets/stickers/animals/bunny-doodle.webp"}},
    {"id": "cat", "name": "마네키네코 복고양이", "meaning": "오른손을 들어 사람과 재물을 부르는 고양이", "tags": ["복", "재물", "인기"], "subject": "maneki-neko lucky cat raising right paw", "weights": {"job": 1, "love": 1, "money": 5, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/cat-y2k.webp", "retro": "assets/stickers/animals/cat-retro.webp", "doodle": "assets/stickers/animals/cat-doodle.webp"}},
    {"id": "puppy", "name": "꼬리치는 댕댕이", "meaning": "조건 없는 사랑과 다정함으로 마음을 녹임", "tags": ["다정", "충성", "인연"], "subject": "tail-wagging puppy", "weights": {"job": 1, "love": 5, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/puppy-y2k.webp", "retro": "assets/stickers/animals/puppy-retro.webp", "doodle": "assets/stickers/animals/puppy-doodle.webp"}},
    {"id": "bear", "name": "든든한 곰돌이", "meaning": "묵직한 존재감으로 곁을 든든히 지켜줌", "tags": ["든든함", "안정", "믿음"], "subject": "sturdy teddy bear", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/bear-y2k.webp", "retro": "assets/stickers/animals/bear-retro.webp", "doodle": "assets/stickers/animals/bear-doodle.webp"}},
    {"id": "squirrel", "name": "도토리 다람쥐", "meaning": "도토리를 차곡차곡 모아 큰 재물로 불림", "tags": ["저축", "알짜", "귀여움"], "subject": "squirrel hugging an acorn", "weights": {"job": 1, "love": 3, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/squirrel-y2k.webp", "retro": "assets/stickers/animals/squirrel-retro.webp", "doodle": "assets/stickers/animals/squirrel-doodle.webp"}},
    {"id": "panda", "name": "포근한 판다", "meaning": "보기만 해도 웃음이 나는 무해한 힐링 덩어리", "tags": ["무해함", "힐링", "인기"], "subject": "cuddly panda", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/animals/panda-y2k.webp", "retro": "assets/stickers/animals/panda-retro.webp", "doodle": "assets/stickers/animals/panda-doodle.webp"}},
    {"id": "duck", "name": "뒤뚱 아기오리", "meaning": "물 위는 고요하고 발밑은 부지런히 저어 목표 도달", "tags": ["꾸준함", "성실", "목표"], "subject": "waddling baby duck", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/animals/duck-y2k.webp", "retro": "assets/stickers/animals/duck-retro.webp", "doodle": "assets/stickers/animals/duck-doodle.webp"}},
    {"id": "chick", "name": "삐약이 병아리", "meaning": "작은 껍질을 깨고 힘차게 나오는 새 생명의 힘", "tags": ["새출발", "탄생", "희망"], "subject": "baby chick hatching from an eggshell", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/animals/chick-y2k.webp", "retro": "assets/stickers/animals/chick-retro.webp", "doodle": "assets/stickers/animals/chick-doodle.webp"}},
    {"id": "owl", "name": "지혜의 부엉이", "meaning": "밤에도 학업과 배움에서 비범한 성과를 냄", "tags": ["밤샘", "학업", "지혜"], "subject": "wise owl", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/animals/owl-y2k.webp", "retro": "assets/stickers/animals/owl-retro.webp", "doodle": "assets/stickers/animals/owl-doodle.webp"}},
    {"id": "deer", "name": "맑은 눈의 꽃사슴", "meaning": "순수하고 맑은 눈망울로 사람들의 마음을 엶", "tags": ["순수", "호감", "청초"], "subject": "sika deer with flower crown", "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/deer-y2k.webp", "retro": "assets/stickers/animals/deer-retro.webp", "doodle": "assets/stickers/animals/deer-doodle.webp"}},
    {"id": "dolphin", "name": "점핑 돌고래", "meaning": "푸른 파도를 시원하게 가르며 자유롭게 헤엄침", "tags": ["자유", "지능", "활기"], "subject": "jumping dolphin over a wave", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/animals/dolphin-y2k.webp", "retro": "assets/stickers/animals/dolphin-retro.webp", "doodle": "assets/stickers/animals/dolphin-doodle.webp"}},
    {"id": "bee", "name": "부지런한 꿀벌", "meaning": "달콤한 결실을 모아 풍성한 꿀단지를 채움", "tags": ["달콤", "결실", "근면"], "subject": "busy honeybee with honey pot", "weights": {"job": 3, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/bee-y2k.webp", "retro": "assets/stickers/animals/bee-retro.webp", "doodle": "assets/stickers/animals/bee-doodle.webp"}},
    {"id": "quokka", "name": "미소천사 쿼카", "meaning": "세상에서 가장 행복한 미소로 액운을 쫓음", "tags": ["미소", "긍정", "무적"], "subject": "smiling quokka", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/animals/quokka-y2k.webp", "retro": "assets/stickers/animals/quokka-retro.webp", "doodle": "assets/stickers/animals/quokka-doodle.webp"}},
    {"id": "cheetah", "name": "쾌속의 치타", "meaning": "망설임 없이 순식간에 기회를 낚아채는 스피드", "tags": ["스피드", "기회포착", "순발력"], "subject": "sprinting cheetah", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/cheetah-y2k.webp", "retro": "assets/stickers/animals/cheetah-retro.webp", "doodle": "assets/stickers/animals/cheetah-doodle.webp"}},
    {"id": "pegasus", "name": "날개 달린 유니콘", "meaning": "꿈에서나 보던 이상이 현실로 펼쳐지는 기적", "tags": ["기적", "신비", "비상"], "subject": "winged pegasus", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/animals/pegasus-y2k.webp", "retro": "assets/stickers/animals/pegasus-retro.webp", "doodle": "assets/stickers/animals/pegasus-doodle.webp"}},
    {"id": "hamster", "name": "볼빵빵 햄스터", "meaning": "양 볼 가득 복을 채워 넣는 알뜰하고 귀여운 풍요", "tags": ["복", "귀여움", "저축"], "subject": "hamster with stuffed cheeks", "weights": {"job": 1, "love": 3, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/hamster-y2k.webp", "retro": "assets/stickers/animals/hamster-retro.webp", "doodle": "assets/stickers/animals/hamster-doodle.webp"}},
    {"id": "bluebird", "name": "행운의 파랑새", "meaning": "멀리서 찾던 행복이 곁에 있음을 알려주는 새", "tags": ["행복", "발견", "우연"], "subject": "lucky bluebird", "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 3, "daily": 4}, "images": {"y2k": "assets/stickers/animals/bluebird-y2k.webp", "retro": "assets/stickers/animals/bluebird-retro.webp", "doodle": "assets/stickers/animals/bluebird-doodle.webp"}},
    {"id": "sloth", "name": "느긋한 나무늘보", "meaning": "세상이 재촉해도 내 페이스를 지키는 여유", "tags": ["마이웨이", "여유", "평온"], "subject": "relaxed sloth hanging on a branch", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/animals/sloth-y2k.webp", "retro": "assets/stickers/animals/sloth-retro.webp", "doodle": "assets/stickers/animals/sloth-doodle.webp"}},
    {"id": "penguin", "name": "용감한 펭귄", "meaning": "차가운 얼음 바다에 가장 먼저 뛰어드는 용기", "tags": ["선구자", "용기", "도전"], "subject": "brave penguin", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/animals/penguin-y2k.webp", "retro": "assets/stickers/animals/penguin-retro.webp", "doodle": "assets/stickers/animals/penguin-doodle.webp"}},
  ],
  place: [
    {"id": "window", "name": "햇살 드는 창가", "meaning": "햇살과 레이스 커튼이 드리운 창가", "tags": ["햇살", "전망", "영감"], "subject": "sunny window with lace curtain", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/places/window-y2k.webp", "retro": "assets/stickers/places/window-retro.webp", "doodle": "assets/stickers/places/window-doodle.webp"}},
    {"id": "rooftop", "name": "노을 지는 루프탑", "meaning": "붉은 노을과 도심 뷰가 시원한 옥상", "tags": ["전망", "해방감", "포부"], "subject": "rooftop at sunset", "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/places/rooftop-y2k.webp", "retro": "assets/stickers/places/rooftop-retro.webp", "doodle": "assets/stickers/places/rooftop-doodle.webp"}},
    {"id": "cozy_cafe", "name": "골목 안 작은 카페", "meaning": "따뜻한 조명과 커피잔이 놓인 아기자기한 카페", "tags": ["대화", "휴식", "아늑함"], "subject": "tiny alley cafe storefront", "weights": {"job": 1, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/places/cozy_cafe-y2k.webp", "retro": "assets/stickers/places/cozy_cafe-retro.webp", "doodle": "assets/stickers/places/cozy_cafe-doodle.webp"}},
    {"id": "bookstore", "name": "비밀 서점 구석", "meaning": "오래된 책들이 가득 꽂힌 아늑한 책장", "tags": ["지혜", "발견", "몰입"], "subject": "cozy wooden bookshelf", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/places/bookstore-y2k.webp", "retro": "assets/stickers/places/bookstore-retro.webp", "doodle": "assets/stickers/places/bookstore-doodle.webp"}},
    {"id": "park_bench", "name": "푸른 공원 벤치", "meaning": "큰 나무 그늘 아래 놓인 초록빛 벤치", "tags": ["자연", "비움", "여유"], "subject": "green park bench under a tree", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/park_bench-y2k.webp", "retro": "assets/stickers/places/park_bench-retro.webp", "doodle": "assets/stickers/places/park_bench-doodle.webp"}},
    {"id": "night_sea", "name": "잔잔한 밤바다", "meaning": "달빛이 비치는 잔잔한 파도와 모래사장", "tags": ["정화", "낭만", "평온"], "subject": "calm night sea with moon", "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/night_sea-y2k.webp", "retro": "assets/stickers/places/night_sea-retro.webp", "doodle": "assets/stickers/places/night_sea-doodle.webp"}},
    {"id": "train_station", "name": "설레는 기차역 플랫폼", "meaning": "여행을 떠나는 기차와 역 플랫폼", "tags": ["출발", "여행", "새시작"], "subject": "train at station platform", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/places/train_station-y2k.webp", "retro": "assets/stickers/places/train_station-retro.webp", "doodle": "assets/stickers/places/train_station-doodle.webp"}},
    {"id": "flower_terrace", "name": "꽃 피는 테라스", "meaning": "화사한 꽃 화분들로 둘러싸인 테라스", "tags": ["꽃", "화사함", "인연"], "subject": "flower-filled terrace", "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/places/flower_terrace-y2k.webp", "retro": "assets/stickers/places/flower_terrace-retro.webp", "doodle": "assets/stickers/places/flower_terrace-doodle.webp"}},
    {"id": "river_bank", "name": "노을빛 한강변", "meaning": "시원한 강바람과 붉은 노을이 비치는 강변", "tags": ["산책", "치유", "여유"], "subject": "riverside at sunset", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/river_bank-y2k.webp", "retro": "assets/stickers/places/river_bank-retro.webp", "doodle": "assets/stickers/places/river_bank-doodle.webp"}},
    {"id": "library_corner", "name": "조용한 도서관 열람실", "meaning": "초록색 독서등과 책이 가지런한 공부 명당", "tags": ["공부", "합격", "몰입"], "subject": "library desk with green banker lamp", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/places/library_corner-y2k.webp", "retro": "assets/stickers/places/library_corner-retro.webp", "doodle": "assets/stickers/places/library_corner-doodle.webp"}},
    {"id": "forest_trail", "name": "피톤치드 숲길", "meaning": "울창한 자작나무 숲길 산책로", "tags": ["건강", "치유", "휴식"], "subject": "birch forest trail", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/forest_trail-y2k.webp", "retro": "assets/stickers/places/forest_trail-retro.webp", "doodle": "assets/stickers/places/forest_trail-doodle.webp"}},
    {"id": "observatory", "name": "밤하늘 천문대", "meaning": "큰 망원경 돔과 쏟아지는 은하수", "tags": ["소원", "꿈", "영감"], "subject": "observatory dome under milky way", "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/places/observatory-y2k.webp", "retro": "assets/stickers/places/observatory-retro.webp", "doodle": "assets/stickers/places/observatory-doodle.webp"}},
    {"id": "theme_park", "name": "네온빛 놀이공원", "meaning": "밤하늘을 수놓는 관람차와 회전목마 불빛", "tags": ["축제", "설렘", "환상"], "subject": "ferris wheel at night", "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/places/theme_park-y2k.webp", "retro": "assets/stickers/places/theme_park-retro.webp", "doodle": "assets/stickers/places/theme_park-doodle.webp"}},
    {"id": "bus_backseat", "name": "버스 맨 뒷자리 창가", "meaning": "빗방울이나 풍경을 바라보는 버스 창가 자리", "tags": ["감성", "나만의시간", "음악"], "subject": "bus window seat with raindrops", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/places/bus_backseat-y2k.webp", "retro": "assets/stickers/places/bus_backseat-retro.webp", "doodle": "assets/stickers/places/bus_backseat-doodle.webp"}},
    {"id": "high_tower", "name": "전망대 꼭대기", "meaning": "도시 야경이 미니어처처럼 내려다보이는 타워", "tags": ["정상", "성취", "전망"], "subject": "observation tower over city", "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/places/high_tower-y2k.webp", "retro": "assets/stickers/places/high_tower-retro.webp", "doodle": "assets/stickers/places/high_tower-doodle.webp"}},
    {"id": "retro_stationery", "name": "추억의 문구점 앞", "meaning": "뽑기 기계와 과자가 놓인 정겨운 문구점", "tags": ["추억", "동심", "즐거움"], "subject": "retro stationery shop with capsule machine", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/retro_stationery-y2k.webp", "retro": "assets/stickers/places/retro_stationery-retro.webp", "doodle": "assets/stickers/places/retro_stationery-doodle.webp"}},
    {"id": "grassy_hill", "name": "바람 부는 잔디 언덕", "meaning": "뭉게구름과 푸른 언덕 위의 피크닉 매트", "tags": ["자유", "피크닉", "여유"], "subject": "grassy hill with picnic blanket", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/places/grassy_hill-y2k.webp", "retro": "assets/stickers/places/grassy_hill-retro.webp", "doodle": "assets/stickers/places/grassy_hill-doodle.webp"}},
    {"id": "attic", "name": "아늑한 비밀 다락방", "meaning": "삼각형 지붕 창문과 쿠션이 가득한 아지트", "tags": ["아지트", "보물", "편안함"], "subject": "cozy attic with round window", "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/places/attic-y2k.webp", "retro": "assets/stickers/places/attic-retro.webp", "doodle": "assets/stickers/places/attic-doodle.webp"}},
    {"id": "lighthouse", "name": "파도치는 하얀 등대", "meaning": "밤바다를 비추는 든든한 빨간 지붕 등대", "tags": ["안내자", "안전", "든든함"], "subject": "white lighthouse with red roof", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/places/lighthouse-y2k.webp", "retro": "assets/stickers/places/lighthouse-retro.webp", "doodle": "assets/stickers/places/lighthouse-doodle.webp"}},
    {"id": "lp_bar", "name": "레트로 LP 뮤직바", "meaning": "턴테이블 위에서 회전하는 바이닐 레코드", "tags": ["레트로", "음악", "분위기"], "subject": "turntable with vinyl record", "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/places/lp_bar-y2k.webp", "retro": "assets/stickers/places/lp_bar-retro.webp", "doodle": "assets/stickers/places/lp_bar-doodle.webp"}},
  ],
  time: [
    {"id": "time_0630", "name": "오전 06:30", "value": "06:30", "meaning": "하루를 가장 먼저 여는 골든타임", "tags": ["새출발", "성실"], "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_0630-y2k.webp", "retro": "assets/stickers/times/time_0630-retro.webp", "doodle": "assets/stickers/times/time_0630-doodle.webp"}},
    {"id": "time_0707", "name": "오전 07:07", "value": "07:07", "meaning": "행운의 7이 겹치는 아침", "tags": ["행운", "설렘"], "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/times/time_0707-y2k.webp", "retro": "assets/stickers/times/time_0707-retro.webp", "doodle": "assets/stickers/times/time_0707-doodle.webp"}},
    {"id": "time_0845", "name": "오전 08:45", "value": "08:45", "meaning": "중요한 일을 시작하기 좋은 시간", "tags": ["기회", "집중"], "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_0845-y2k.webp", "retro": "assets/stickers/times/time_0845-retro.webp", "doodle": "assets/stickers/times/time_0845-doodle.webp"}},
    {"id": "time_0930", "name": "오전 09:30", "value": "09:30", "meaning": "계획이 척척 풀리는 시간", "tags": ["계획", "효율"], "weights": {"job": 5, "love": 1, "money": 3, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_0930-y2k.webp", "retro": "assets/stickers/times/time_0930-retro.webp", "doodle": "assets/stickers/times/time_0930-doodle.webp"}},
    {"id": "time_1111", "name": "오전 11:11", "value": "11:11", "meaning": "소원을 빌기 좋은 시간", "tags": ["기적", "인연"], "weights": {"job": 1, "love": 3, "money": 3, "people": 3, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/times/time_1111-y2k.webp", "retro": "assets/stickers/times/time_1111-retro.webp", "doodle": "assets/stickers/times/time_1111-doodle.webp"}},
    {"id": "time_1230", "name": "오후 12:30", "value": "12:30", "meaning": "누군가와 대화하기 좋은 점심", "tags": ["대화", "연결"], "weights": {"job": 1, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_1230-y2k.webp", "retro": "assets/stickers/times/time_1230-retro.webp", "doodle": "assets/stickers/times/time_1230-doodle.webp"}},
    {"id": "time_1414", "name": "오후 02:14", "value": "14:14", "meaning": "마음을 전하기 좋은 오후", "tags": ["사랑", "고백"], "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_1414-y2k.webp", "retro": "assets/stickers/times/time_1414-retro.webp", "doodle": "assets/stickers/times/time_1414-doodle.webp"}},
    {"id": "time_1533", "name": "오후 03:33", "value": "15:33", "meaning": "집중력이 다시 차오르는 시간", "tags": ["몰입", "집중"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_1533-y2k.webp", "retro": "assets/stickers/times/time_1533-retro.webp", "doodle": "assets/stickers/times/time_1533-doodle.webp"}},
    {"id": "time_1730", "name": "오후 05:30", "value": "17:30", "meaning": "하루의 결실을 확인하는 시간", "tags": ["결실", "성취"], "weights": {"job": 3, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_1730-y2k.webp", "retro": "assets/stickers/times/time_1730-retro.webp", "doodle": "assets/stickers/times/time_1730-doodle.webp"}},
    {"id": "time_1907", "name": "오후 07:07", "value": "19:07", "meaning": "설렘이 찾아오는 저녁", "tags": ["설렘", "낭만"], "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_1907-y2k.webp", "retro": "assets/stickers/times/time_1907-retro.webp", "doodle": "assets/stickers/times/time_1907-doodle.webp"}},
    {"id": "time_2000", "name": "오후 08:00", "value": "20:00", "meaning": "나를 위해 쉬어가는 시간", "tags": ["휴식", "힐링"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/times/time_2000-y2k.webp", "retro": "assets/stickers/times/time_2000-retro.webp", "doodle": "assets/stickers/times/time_2000-doodle.webp"}},
    {"id": "time_2222", "name": "오후 10:22", "value": "22:22", "meaning": "조용히 영감이 떠오르는 밤", "tags": ["영감", "직관"], "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 2}, "images": {"y2k": "assets/stickers/times/time_2222-y2k.webp", "retro": "assets/stickers/times/time_2222-retro.webp", "doodle": "assets/stickers/times/time_2222-doodle.webp"}},
  ],
  symbol: [
    {"id": "star", "name": "오색 반짝이 별", "meaning": "어둠 속 앞길을 비춰주는 스파클 스타", "tags": ["희망", "길잡이", "빛"], "subject": "four-point sparkle star", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/star-y2k.webp", "retro": "assets/stickers/symbols/star-retro.webp", "doodle": "assets/stickers/symbols/star-doodle.webp"}},
    {"id": "rainbow", "name": "비 온 뒤 무지개", "meaning": "비바람 뒤 찾아오는 7색 찬란한 무지개", "tags": ["희망", "약속", "선물"], "subject": "rainbow arch with clouds", "weights": {"job": 1, "love": 5, "money": 1, "people": 3, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/symbols/rainbow-y2k.webp", "retro": "assets/stickers/symbols/rainbow-retro.webp", "doodle": "assets/stickers/symbols/rainbow-doodle.webp"}},
    {"id": "heart_spark", "name": "두근 하트", "meaning": "날개와 반짝이가 돋아난 사랑스러운 하트", "tags": ["사랑", "진심", "애정"], "subject": "winged sparkle heart", "weights": {"job": 1, "love": 5, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/heart_spark-y2k.webp", "retro": "assets/stickers/symbols/heart_spark-retro.webp", "doodle": "assets/stickers/symbols/heart_spark-doodle.webp"}},
    {"id": "lightning", "name": "짜릿한 번개", "meaning": "막힌 속을 단번에 뚫어주는 네온 번개", "tags": ["스피드", "결단", "파워"], "subject": "neon yellow lightning bolt", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/lightning-y2k.webp", "retro": "assets/stickers/symbols/lightning-retro.webp", "doodle": "assets/stickers/symbols/lightning-doodle.webp"}},
    {"id": "smile", "name": "해피 스마일", "meaning": "액운을 물리치는 노란색 클래식 스마일", "tags": ["미소", "긍정", "무탈"], "subject": "yellow smiley face", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/smile-y2k.webp", "retro": "assets/stickers/symbols/smile-retro.webp", "doodle": "assets/stickers/symbols/smile-doodle.webp"}},
    {"id": "crescent_moon", "name": "은빛 초승달", "meaning": "밤하늘을 밝히며 영감을 깨우는 초승달", "tags": ["직관", "지혜", "평온"], "subject": "crescent moon with tiny stars", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 4}, "images": {"y2k": "assets/stickers/symbols/crescent_moon-y2k.webp", "retro": "assets/stickers/symbols/crescent_moon-retro.webp", "doodle": "assets/stickers/symbols/crescent_moon-doodle.webp"}},
    {"id": "four_leaf_clover", "name": "황금 클로버", "meaning": "기적 같은 대행운의 상징", "tags": ["대행운", "기적", "축복"], "subject": "golden four-leaf clover emblem", "weights": {"job": 1, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/four_leaf_clover-y2k.webp", "retro": "assets/stickers/symbols/four_leaf_clover-retro.webp", "doodle": "assets/stickers/symbols/four_leaf_clover-doodle.webp"}},
    {"id": "angel_wings", "name": "수호 천사의 날개", "meaning": "나를 안전하게 감싸주는 하얀 깃털 날개", "tags": ["보호", "가호", "안전"], "subject": "white angel wings", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/angel_wings-y2k.webp", "retro": "assets/stickers/symbols/angel_wings-retro.webp", "doodle": "assets/stickers/symbols/angel_wings-doodle.webp"}},
    {"id": "butterfly", "name": "나비의 날갯짓", "meaning": "거대한 행운의 바람을 일으키는 오색 나비", "tags": ["변화", "도약", "나비효과"], "subject": "colorful butterfly", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 4}, "images": {"y2k": "assets/stickers/symbols/butterfly-y2k.webp", "retro": "assets/stickers/symbols/butterfly-retro.webp", "doodle": "assets/stickers/symbols/butterfly-doodle.webp"}},
    {"id": "spark_fire", "name": "열정의 불꽃", "meaning": "활활 타오르는 도전과 에너지의 불꽃", "tags": ["열정", "추진", "성취"], "subject": "flame", "weights": {"job": 5, "love": 1, "money": 1, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/spark_fire-y2k.webp", "retro": "assets/stickers/symbols/spark_fire-retro.webp", "doodle": "assets/stickers/symbols/spark_fire-doodle.webp"}},
    {"id": "neon_diamond", "name": "네온 다이아몬드", "meaning": "어떤 충격에도 부서지지 않는 단단함", "tags": ["가치", "영원", "단단함"], "subject": "neon diamond gem", "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/neon_diamond-y2k.webp", "retro": "assets/stickers/symbols/neon_diamond-retro.webp", "doodle": "assets/stickers/symbols/neon_diamond-doodle.webp"}},
    {"id": "peace_dove", "name": "평화의 비둘기", "meaning": "올리브 가지를 문 하얀 평화의 비둘기", "tags": ["평화", "화해", "원만"], "subject": "white dove with olive branch", "weights": {"job": 1, "love": 1, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/peace_dove-y2k.webp", "retro": "assets/stickers/symbols/peace_dove-retro.webp", "doodle": "assets/stickers/symbols/peace_dove-doodle.webp"}},
    {"id": "horseshoe", "name": "행운의 편자", "meaning": "복을 담아두는 U자형 행운의 말발굽", "tags": ["복주머니", "편자", "재물"], "subject": "lucky horseshoe", "weights": {"job": 1, "love": 1, "money": 5, "people": 1, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/horseshoe-y2k.webp", "retro": "assets/stickers/symbols/horseshoe-retro.webp", "doodle": "assets/stickers/symbols/horseshoe-doodle.webp"}},
    {"id": "sun_emblem", "name": "찬란한 태양", "meaning": "모든 어둠을 몰아내는 햇살 가득 태양", "tags": ["생명력", "승리", "광명"], "subject": "smiling sun emblem", "weights": {"job": 3, "love": 1, "money": 3, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/sun_emblem-y2k.webp", "retro": "assets/stickers/symbols/sun_emblem-retro.webp", "doodle": "assets/stickers/symbols/sun_emblem-doodle.webp"}},
    {"id": "magic_eye", "name": "진실의 눈", "meaning": "거짓을 가려내고 귀인을 알아보는 눈동자", "tags": ["혜안", "통찰", "보호"], "subject": "mystic evil-eye charm", "weights": {"job": 3, "love": 1, "money": 1, "people": 1, "study": 5, "daily": 4}, "images": {"y2k": "assets/stickers/symbols/magic_eye-y2k.webp", "retro": "assets/stickers/symbols/magic_eye-retro.webp", "doodle": "assets/stickers/symbols/magic_eye-doodle.webp"}},
    {"id": "angel_halo", "name": "황금빛 엔젤 링", "meaning": "머리 위에 떠오르는 천사의 링과 빛무리", "tags": ["선함", "축복", "보호"], "subject": "golden halo ring", "weights": {"job": 1, "love": 1, "money": 1, "people": 3, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/angel_halo-y2k.webp", "retro": "assets/stickers/symbols/angel_halo-retro.webp", "doodle": "assets/stickers/symbols/angel_halo-doodle.webp"}},
    {"id": "lucky_knot", "name": "행운의 리본 매듭", "meaning": "인연과 복을 단단히 묶어주는 매듭", "tags": ["인연", "약속", "매듭"], "subject": "traditional lucky knot", "weights": {"job": 1, "love": 5, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/lucky_knot-y2k.webp", "retro": "assets/stickers/symbols/lucky_knot-retro.webp", "doodle": "assets/stickers/symbols/lucky_knot-doodle.webp"}},
    {"id": "music_note", "name": "흥겨운 음표", "meaning": "콧노래가 절로 나오는 경쾌한 음표", "tags": ["즐거움", "음악", "신남"], "subject": "pair of eighth notes", "weights": {"job": 1, "love": 1, "money": 1, "people": 1, "study": 3, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/music_note-y2k.webp", "retro": "assets/stickers/symbols/music_note-retro.webp", "doodle": "assets/stickers/symbols/music_note-doodle.webp"}},
    {"id": "crystal_prism", "name": "오색 프리즘", "meaning": "하나의 빛이 일곱 빛깔로 갈라지는 프리즘", "tags": ["다채로움", "매력", "변화"], "subject": "prism splitting light", "weights": {"job": 1, "love": 3, "money": 1, "people": 1, "study": 1, "daily": 5}, "images": {"y2k": "assets/stickers/symbols/crystal_prism-y2k.webp", "retro": "assets/stickers/symbols/crystal_prism-retro.webp", "doodle": "assets/stickers/symbols/crystal_prism-doodle.webp"}},
    {"id": "cherry_pair", "name": "쌍둥이 체리", "meaning": "하나의 꼭지에 꼭 붙어 있는 체리 한 쌍", "tags": ["단짝", "커플", "우정"], "subject": "pair of cherries", "weights": {"job": 1, "love": 3, "money": 1, "people": 5, "study": 1, "daily": 2}, "images": {"y2k": "assets/stickers/symbols/cherry_pair-y2k.webp", "retro": "assets/stickers/symbols/cherry_pair-retro.webp", "doodle": "assets/stickers/symbols/cherry_pair-doodle.webp"}},
  ],
};

// 브라우저 전역 + (필요 시) 모듈 양쪽에서 사용 가능
if (typeof window !== "undefined") {
  Object.assign(window, { FORTUNE_TYPES, STICKER_STYLES, CATEGORIES, EXCLUSIONS, FORTUNE_DATA });
}
if (typeof module !== "undefined") {
  module.exports = { FORTUNE_TYPES, STICKER_STYLES, CATEGORIES, EXCLUSIONS, FORTUNE_DATA };
}
